# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "nav"
name = "AI导航"
url = "https://ai.laosji.net"
[main.params]
icon = "menu-nav"
newtab = true

[[social]]
identifier = "导航"
name = "导航"
url = "https://dh.laosji.net"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/laosji188937"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "wechat"
name = "wecaht"
url = "https://mp.weixin.qq.com/s/BLnizy3_WDwrgBElva8A3Q"

[social.params]
icon = "brand-wechat"

[[social]]
identifier = "pokeai"
name = "pokeai"
url = "https://emoecho.com"

[social.params]
icon = "pokeai-app"