name: Deploy to Github Pages

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:
    workflow_run:
        workflows: ["Sync YouTube Videos", "Sync Notion to Hugo"]
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        if: |
            github.event_name != 'workflow_run' ||
            github.event.workflow_run.conclusion == 'success'

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Cache Hugo resources
              uses: actions/cache@v4
              env:
                  cache-name: cache-hugo-resources
              with:
                  path: resources
                  key: ${{ env.cache-name }}

            - uses: actions/setup-go@v4
              with:
                  go-version: "stable"
            - run: go version

            - name: Cache Go Modules
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build
              run: hugo --minify --gc

            - name: Deploy 🚀
              if: github.event_name != 'pull_request'
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: public
                  cname: www.laosji.net
                  clean: true
                  single-commit: true
